export const G_CODES: Record<string, string> = {
  G0: 'Rapid positioning (non-cutting move at max speed).',
  G1: 'Linear interpolation (cutting move at the programmed feed rate).',
  G2: 'Circular interpolation, clockwise arc.',
  G3: 'Circular interpolation, counter-clockwise arc.',
  G4: 'Dwell — pause the program for a specified time (P in seconds/ms).',
  G17: 'Select the XY plane for arc/circular moves.',
  G18: 'Select the XZ plane for arc/circular moves.',
  G19: 'Select the YZ plane for arc/circular moves.',
  G20: 'Set units to inches.',
  G21: 'Set units to millimeters.',
  G28: "Return to the machine's home/reference position.",
  G40: 'Cancel cutter compensation.',
  G41: 'Cutter compensation left.',
  G42: 'Cutter compensation right.',
  G43: 'Tool length compensation, positive.',
  G49: 'Cancel tool length compensation.',
  G54: 'Select work coordinate system 1.',
  G55: 'Select work coordinate system 2.',
  G80: 'Cancel canned (fixed) cycle.',
  G81: 'Simple drilling canned cycle.',
  G82: 'Drilling canned cycle with dwell.',
  G83: 'Peck drilling canned cycle.',
  G90: 'Absolute positioning mode.',
  G91: 'Incremental positioning mode.',
  G92: 'Set/offset the current position (coordinate system shift).',
};

export const M_CODES: Record<string, string> = {
  M0: 'Program pause (unconditional stop).',
  M1: 'Optional program stop.',
  M2: 'End of program.',
  M3: 'Start spindle, clockwise rotation.',
  M4: 'Start spindle, counter-clockwise rotation.',
  M5: 'Stop spindle.',
  M6: 'Tool change.',
  M7: 'Mist coolant on.',
  M8: 'Flood coolant on.',
  M9: 'Coolant off.',
  M30: 'End of program and rewind to the start.',
};

export const WORD_PARAMS: string[] = [
  'X',
  'Y',
  'Z',
  'A',
  'B',
  'C',
  'I',
  'J',
  'K',
  'R',
  'F',
  'S',
  'T',
  'P',
  'Q',
  'L',
  'H',
  'D',
  'E',
];
