export const FRONTEND_MESSAGE_CONSTANTS = {
  SUCCESS: {
    LOGOUT: 'Logged out successfully',
    LOGIN: 'Login Successful',
    PASSWORD_RESET: 'Password reset successfully! Please sign in.',
    PASSWORD_RESET_LINK_SENT:
      'Password reset link sent! Please check your email.',
    VERIFICATION_EMAIL_SENT: 'Verification email sent successfully',
    TENANT_CREATED: 'Tenant created successfully',
    TENANT_UPDATED: 'Tenant updated successfully',
    TENANT_BLOCKED: 'Tenant blocked',
    TENANT_UNBLOCKED: 'Tenant unblocked',
    TENANT_NAME_UPDATED: 'Tenant name updated',
    USER_BLOCKED: 'User blocked',
    USER_UNBLOCKED: 'User unblocked',
    MACHINE_CREATED: 'Machine created successfully',
    MACHINE_UPDATED: 'Machine updated successfully',
    MACHINE_DELETED: 'Machine deleted successfully',
    MACHINE_BLOCK_TOGGLED: 'Machine status updated',
    FIXTURE_CREATED: 'Fixture created successfully',
    FIXTURE_UPDATED: 'Fixture updated successfully',
    FIXTURE_DELETED: 'Fixture deleted successfully',
    FIXTURE_BLOCK_TOGGLED: 'Fixture status updated',
    EMPLOYEE_CREATED: 'Employee created successfully',
    EMPLOYEE_UPDATED: 'Employee updated successfully',
    EMPLOYEE_DELETED: 'Employee deleted successfully',
    EMPLOYEE_BLOCK_TOGGLED: 'Employee status updated',
  },
  ERROR: {
    LOGOUT_FAILED: 'Logout failed',
    TOKEN_REQUIRED: 'Token is required',
    SOMETHING_WENT_WRONG: 'Something went wrong',
    INVALID_RESET_LINK:
      'Invalid or expired reset link. Please request a new one.',
    SESSION_EXPIRED: 'Session expired. Please register again.',
    FAILED_RESEND_EMAIL: 'Failed to resend email',
    TENANT_CREATION_FAILED: 'Tenant creation failed',
    TENANT_BLOCKED_OR_DELETED: 'Tenant is blocked or deleted',
    SOMETHING_WENT_WRONG_TRY_AGAIN: 'Something went wrong please try again',
    FAILED_FETCH_TENANTS: 'Failed to fetch tenants',
    FAILED_UPDATE_TENANT_NAME: 'Failed to update tenant name',
    TENANT_NAME_TAKEN:
      'Organization name is already taken. Please try another.',
    FAILED_FETCH_USERS: 'Failed to fetch users',
    FAILED_FETCH_MACHINES: 'Failed to fetch machines',
    MACHINE_CREATION_FAILED: 'Machine creation failed',
    MACHINE_UPDATE_FAILED: 'Machine update failed',
    FAILED_FETCH_FIXTURES: 'Failed to fetch fixtures',
    FIXTURE_CREATION_FAILED: 'Fixture creation failed',
    FIXTURE_UPDATE_FAILED: 'Fixture update failed',
    FAILED_FETCH_EMPLOYEES: 'Failed to fetch employees',
    EMPLOYEE_CREATION_FAILED: 'Employee creation failed',
    EMPLOYEE_UPDATE_FAILED: 'Employee update failed',
  },
  VALIDATION: {
    PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
    VALIDATION_ERROR: 'Validation error',
    INVALID_EMAIL: 'Invalid email address',
    PASSWORD_MIN_LENGTH_6: 'Password must be at least 6 characters long',
    PASSWORD_MAX_LENGTH_12: 'Password must be at most 12 characters long',
    NAME_MIN_LENGTH_3: 'Name must be at least 3 characters long',
  },
};
