export const FRONTEND_MESSAGE_CONSTANTS = {
  SUCCESS: {
    LOGOUT: 'Logged out successfully',
    LOGIN: 'Login Successful',
    PASSWORD_RESET: 'Password reset successfully! Please sign in.',
    PASSWORD_RESET_LINK_SENT:
      'Password reset link sent! Please check your email.',
    VERIFICATION_EMAIL_SENT: 'Verification email sent successfully',
    TENANT_CREATED: 'Tenant created successfully',
    TENANT_UPDATED: 'Tenant updated successfully',
    TENANT_BLOCKED: 'Tenant blocked',
    TENANT_UNBLOCKED: 'Tenant unblocked',
    TENANT_NAME_UPDATED: 'Tenant name updated',
    USER_BLOCKED: 'User blocked',
    USER_UNBLOCKED: 'User unblocked',
    MACHINE_CREATED: 'Machine created successfully',
    MACHINE_UPDATED: 'Machine updated successfully',
    MACHINE_DELETED: 'Machine deleted successfully',
    MACHINE_BLOCK_TOGGLED: 'Machine status updated',
    FIXTURE_CREATED: 'Fixture created successfully',
    FIXTURE_UPDATED: 'Fixture updated successfully',
    FIXTURE_DELETED: 'Fixture deleted successfully',
    FIXTURE_BLOCK_TOGGLED: 'Fixture status updated',
    EMPLOYEE_CREATED: 'Employee created successfully',
    EMPLOYEE_UPDATED: 'Employee updated successfully',
    EMPLOYEE_DELETED: 'Employee deleted successfully',
    EMPLOYEE_BLOCK_TOGGLED: 'Employee status updated',
    PLAN_CREATED: 'Plan created successfully',
    PLAN_UPDATED: 'Plan updated successfully',
    PLAN_DELETED: 'Plan deleted successfully',
    PLAN_BLOCK_TOGGLED: 'Plan status updated',
    RAW_MATERIAL_CREATED: 'Raw material created successfully',
    RAW_MATERIAL_UPDATED: 'Raw material updated successfully',
    RAW_MATERIAL_DELETED: 'Raw material deleted successfully',
    RAW_MATERIAL_BLOCK_TOGGLED: 'Raw material status updated',
    JOB_CREATED: 'Job created successfully',
    JOB_UPDATED: 'Job updated successfully',
    JOB_DELETED: 'Job deleted successfully',
    PART_CREATED: 'Part created successfully',
    PART_UPDATED: 'Part updated successfully',
    PART_DELETED: 'Part deleted successfully',
    PART_BLOCK_TOGGLED: 'Part status updated',
    SHIFT_TEMPLATE_CREATED: 'Shift template created successfully',
    SHIFT_TEMPLATE_UPDATED: 'Shift template updated successfully',
    SHIFT_TEMPLATE_DELETED: 'Shift template deleted successfully',
    PRODUCTION_SHIFT_GENERATED: 'Production shift generated for today!',
    SHIFT_JOB_PROGRESS_UPDATED: 'Job progress updated',
    NC_PROGRAM_CREATED: 'NC Program created successfully',
    NC_PROGRAM_UPDATED: 'NC Program updated successfully',
    VERSION_BLOCKED: 'Version blocked successfully',
    VERSION_UNBLOCKED: 'Version unblocked successfully',
    VERSION_DELETED: 'Version deleted successfully',
    VERSION_ADDED: 'New version uploaded successfully',
  },
  ERROR: {
    INVALID_INCREMENT_QUANTITY: 'Enter how many pieces you completed',
    PART_INFORMATION_NOT_AVAILABLE: 'Part information not available',
    FAILED_TO_LOAD_PART_DETAILS: 'Failed to load part details',
    LOGOUT_FAILED: 'Logout failed',
    TOKEN_REQUIRED: 'Token is required',
    SOMETHING_WENT_WRONG: 'Something went wrong',
    INVALID_RESET_LINK:
      'Invalid or expired reset link. Please request a new one.',
    SESSION_EXPIRED: 'Session expired. Please register again.',
    FAILED_RESEND_EMAIL: 'Failed to resend email',
    TENANT_CREATION_FAILED: 'Tenant creation failed',
    TENANT_BLOCKED_OR_DELETED: 'Tenant is blocked or deleted',
    SOMETHING_WENT_WRONG_TRY_AGAIN: 'Something went wrong please try again',
    FAILED_FETCH_TENANTS: 'Failed to fetch tenants',
    FAILED_UPDATE_TENANT_NAME: 'Failed to update tenant name',
    TENANT_NAME_TAKEN:
      'Organization name is already taken. Please try another.',
    FAILED_FETCH_USERS: 'Failed to fetch users',
    FAILED_FETCH_MACHINES: 'Failed to fetch machines',
    MACHINE_CREATION_FAILED: 'Machine creation failed',
    MACHINE_UPDATE_FAILED: 'Machine update failed',
    FAILED_FETCH_FIXTURES: 'Failed to fetch fixtures',
    FIXTURE_CREATION_FAILED: 'Fixture creation failed',
    FIXTURE_UPDATE_FAILED: 'Fixture update failed',
    FAILED_FETCH_RAW_MATERIALS: 'Failed to fetch raw materials',
    RAW_MATERIAL_CREATION_FAILED: 'Raw material creation failed',
    RAW_MATERIAL_UPDATE_FAILED: 'Raw material update failed',
    FAILED_FETCH_EMPLOYEES: 'Failed to fetch employees',
    EMPLOYEE_CREATION_FAILED: 'Employee creation failed',
    EMPLOYEE_UPDATE_FAILED: 'Employee update failed',
    FAILED_FETCH_JOBS: 'Failed to fetch jobs',
    JOB_CREATION_FAILED: 'Job creation failed',
    JOB_UPDATE_FAILED: 'Job update failed',
    FAILED_FETCH_PARTS: 'Failed to fetch parts',
    PART_CREATION_FAILED: 'Part creation failed',
    PART_UPDATE_FAILED: 'Part update failed',
    FAILED_FETCH_PLANS: 'Failed to fetch plans',
    FAILED_UPDATE_PLAN: 'Failed to update plan',
    FAILED_DELETE_PLAN: 'Failed to delete plan',
    SUBSCRIPTION_EXPIRED:
      'Access blocked: Your subscription has expired. Please unblock to continue.',
    SUBSCRIPTION_CANCELLED:
      'Access blocked: Your access has been manually blocked. Please unblock to restore platform access.',
    SUBSCRIPTION_INACTIVE:
      'No active subscription found for your organization.',
    PAYMENT_FAILED_REASON: 'Payment failed: {reason}. Please try again.',
    PAYMENT_VERIFICATION_FAILED:
      'Payment verification failed. Please contact support.',
    RAZORPAY_LOAD_FAILED:
      'Could not load payment gateway. Please check your connection.',
    ACCESS_RESTRICTED_EMPLOYEE:
      'Organization access suspended. Contact your administrator.',
    FAILED_FETCH_NC_PROGRAMS: 'Failed to fetch NC Programs',
    NC_PROGRAM_CREATION_FAILED: 'NC Program creation failed',
    NC_PROGRAM_UPDATE_FAILED: 'NC Program update failed',
    VERSION_BLOCK_FAILED: 'Failed to update version block status',
    VERSION_DELETE_FAILED: 'Failed to delete version',
    VERSION_ADD_FAILED: 'Failed to add new version',
    FAILED_FETCH_SHIFT_TEMPLATES: 'Failed to fetch shift templates',
    SHIFT_TEMPLATE_CREATION_FAILED: 'Shift template creation failed',
    SHIFT_TEMPLATE_UPDATE_FAILED: 'Shift template update failed',
    SHIFT_TEMPLATE_DELETION_FAILED: 'Shift template deletion failed',
    FAILED_FETCH_PRODUCTION_SHIFTS: 'Failed to fetch production shifts',
    PRODUCTION_SHIFT_GENERATION_FAILED: 'Production shift generation failed',
    SHIFT_JOB_PROGRESS_UPDATE_FAILED: 'Shift job progress update failed',
    FAILED_FETCH_DASHBOARD: 'Failed to fetch dashboard statistics',
    VALIDATION_DATE_REQUIRED: 'Start date and End date are required.',
    VALIDATION_DATE_END_BEFORE_START: 'End date cannot be before start date.',
    FAILED_FETCH_REVENUE: 'Failed to fetch revenue statistics',
    REVENUE_NO_EXPORT_DATA: 'No transaction data to export.',
  },
  VALIDATION: {
    PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
    VALIDATION_ERROR: 'Validation error',
    INVALID_EMAIL: 'Invalid email address',
    PASSWORD_MIN_LENGTH_6: 'Password must be at least 6 characters long',
    PASSWORD_MAX_LENGTH_12: 'Password must be at most 12 characters long',
    NAME_MIN_LENGTH_3: 'Name must be at least 3 characters long',
  },
};
